language: node_js
cache: yarn
node_js:
- node
script:
- npm run flow
- npm run test
- npm run build
- npm run lint
deploy:
  provider: firebase
  on:
    branch: master
  token:
    secure: XRkjCWi42iTg38tXzlVm5pewUMpjJt75suGK1USkiMYNkPSNJPJ4PAVLsJDlE5DajRhrg9tbV+1vk7NhIZqaRRdS65HMFhEC4PnCgS0DI6lkQq/lOvj7kOsqS+N94vMOda/18zrvIx9B+dadvFWI8FOEQKhrXSJJBpOOklbayxtm1opi1FhjyBfsNFArm8iuMtvYrfeu3iVd7wunMnuSIV58i7YKURX634OyryWRZrxgIbOgpMmWYK1IylSLtcy0GOyi/wxfwePQP/zB2fLXm+QZstgqKCZdz0kpx+ENoP8UzcIhNNtnwjTHmECWwNYhh07EfL6OhAyhBp9SjsdgQ7sahqNMPdaQt5CLPB525kiUFV5IYKvZAPBt+waq5RuDgtn8UtqO9U/wKzB5sy7dq4fTmOw+CrbfJb/XKd4DuT3AOJVw5JwCrFvfN/bo8klMLmYsHVUoRifiNJjdYGynfMqRzLlpf0iZ75pOsbJXV+B8/26bF13HDV5AibMAmNRnCbFSQwiNDFCgdaU8YWIVrsesNXyGLBkXNQqZE4g8cJFS2CTNxIYEjM1a/zcjWC1nCuUEv8suqiLWkv1flug/yahxxONP6Q+3dciMFl3+q/lBrByeVgUxUDmfhUV7lu+vn99ReE8jteQNdZ6X6Ta0pYzTE3bqubZ8fgNOCBgXSGc=
