language: node_js
cache: yarn
node_js:
- node
script:
- npm run flow
- npm run test
- npm run build
- npm run lint
deploy:
  provider: firebase
  on:
    branch: master
  skip_cleanup: true
  token:
    secure: "MMPPmF4dKouBf5w++cy1PE/n9hD17EHbl1lVj91YAT+1UN4LJN+gbb2dxRyw4SrGU3TKdskOaQGAoILOAjRa2Ly41+42SL5VmNS4mAPYPFWF/XcID8gHvyWd5o6eqU547/VkqrKlLRlSkwoc7DkkNNm0EyUj4x931Kzf9k7taV7ygAI0DMBruybyt6YbhFmcC+BwRzBoSn9HiGsyOOT8r/ogOPV9gqz2rmOGdLGj0tMim/JvhFEhbbVHoGVxAtpmbUqpiWoeuD+16Y5eAXBMdXIVhZRy9QDfUW2UNQPX/dxZ2+v3rVdt2J0h51B7jSvTvLywrxbTkKtbZpWJuV7xc2nKXoDuG6IXfObUXjcFx28sCzDvIQe0A5ZSMpXjkvMLAzvIOMmJT3wtbtattIbgvP3FSYAjvc588B27CXPl2kAz2BiLxBGpbmKRAEpk1sorzSSDlnrXJKMDBFgbo8yuEoZfDeBfEijeUFMwptsuymHXs2PX9klWwFSdNy4F+Q9p4tCDF8JJdI6mwNgZTsmWKj+rey0vQPwAEauR9O4SQMs038rfY+i0CE3G4IoCZc7AAnb4PpHFg+MTrYJJ5uNJWdqmUM4r4LFNi61omLg0q4AnoqVAsA0oVeS1DeBnqdP5wI4PDdAuXgGB2pBwLg8QrJ8TOQUjYSOUjaTJSf+J9yI="
