language: node_js
cache: yarn
node_js:
- node
script:
- npm run flow
- npm run test
- npm run build
- npm run lint
deploy:
  provider: firebase
  on:
    branch: master
  token:
    secure: GkDD1t58b0LzdRu7lc1KoiNcviJUhzQMUrVHzBIveq+gep68x2yCnc43m758jl+TG73pSSTCADR/593Qa07gZFoB9JJQ1rMOiMkU0DpZHo9CNWxt6Ypd6LH3Thm+dQ1PsTdewbPM1BInXs3tR3k9leC2PiPvhGX2hZg4t67WVe/lIUJqkwpvX7ZsateL3zQoZRha2UtrqUqOLrJAVV9RAk8OhO6F5R8EQEOzQHcTGghrn43GZ7yR3VYLz+me0ToES+uGTZquIcTYYozlqkUaUb0ZMf8vbqpy30HR2DJZNAzOSj/cWJB280IqkXtdcyC2iD3nRJSyOgottoh1z7o6ZLK21dPRJX58MhCNgeoBYLq7i8rHJB0AIVwkmqdlWcY3o8nNffMASFhYeu6mqkqwTASpkB7CSxp0DPpnT0tRTVbNgoZpXSE/beax02igHDlNta+4BGTn1/po2hJLwNP9D+KaaQRH2C5JuqZGZr/cTClu9SCXGkqX4Z+aQ1MLQy09UNqW+SCHNTBno7aomWzBd+FkRx0flDx6GuwfPK8cPJgn2PhRxecjuBJ4yZRTDV6PnQWZEBfXdmWwx3LgjF6LkVX7wssxcdsXzgVRHoHoD5dDOCbT+P/coSJpSRq00k30/AIneMv7m41uKTVToKCKXM1oTMtr5rL+EynI8nnyEww=
