language: node_js
cache: yarn
node_js:
- node
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
- yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- npm run flow
- npm run test:coverage
- npm run build
- npm run lint
after_script: greenkeeper-lockfile-upload
deploy:
  provider: firebase
  token: "$FIREBASE_TOKEN"
  skip_cleanup: true
  on:
    branch: master
env:
  global:
    secure: CI68C7HlpXJnwRPQTBv73UvpQESI80HPKtjwsTgVbRZHKf7xwN/+wjvfZIZ6SoA2ckpWDuVWRxvJT2qRJCtniRr3A2mvqh/gW4XKJAciGXs7uZg58x56Fwqppc3zue+YtH/Rmkug8URH4w+2+hQ2sLtqsS17w1lA3GOiJ+Hm/OTYpslatS2dVh4NjhP8yNIOymsZY19M4P6CxljrQKbMiATWjZUXB22WnQapwQ7LIqFbSfwa3AtW86mzdIuq7ysJh9KdR7hP9adB6fFC6nwtdsNLXSnhn9cESpMFgpKVKpt4C//Rcohgu0cWAIfWis1FQ+SRioN38Kf9rQ576/6oznLXWCnJP66yqqReNVljofhCvK1kAKQkLnfvOEfAB2vBmAQT/dO5o0C3KruqNSlAGMTIHynJiJcxL2H8MNkCJr0cVjsdH4ysViGeGEVqty/dSws8zWCABAIcNec01kJbcQWoAPXIZbtHMugTbfPrJB871/6Jjo+RB/wF4Vuc+n6VTsfUJCPCL7pxe75+EtvhPg0mRuJ51efhtNILhcOa5GE55VrQMT7ypmM5GCIaImMIfjnAV7NVsMisHHwGTFZTqsr5q4iSgVp7K/50Irg9SPz5N9crp5MoPuQp/r40pb+WIAW8msN3xrjnV+c9bnUjumILVCgakawiPQr+V6AAre8=
